services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: rails_app_production
    restart: unless-stopped

  web:
    image: rails-app-web:latest  # Use the pre-built working image
    ports:
      - "3001:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: production
      DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@db/rails_app_production
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    restart: unless-stopped

volumes:
  postgres_data: